// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BarcodeType.proto

package de.ku.sfl.connection.messages;

/**
 * Protobuf enum {@code de.ku.sfl.connection.messages.BarcodeType}
 */
public enum BarcodeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>EAN_128 = 0;</code>
   */
  EAN_128(0),
  /**
   * <code>DATA_MATRIX = 1;</code>
   */
  DATA_MATRIX(1),
  /**
   * <code>PDF417 = 2;</code>
   */
  PDF417(2),
  ;

  /**
   * <code>EAN_128 = 0;</code>
   */
  public static final int EAN_128_VALUE = 0;
  /**
   * <code>DATA_MATRIX = 1;</code>
   */
  public static final int DATA_MATRIX_VALUE = 1;
  /**
   * <code>PDF417 = 2;</code>
   */
  public static final int PDF417_VALUE = 2;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BarcodeType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static BarcodeType forNumber(int value) {
    switch (value) {
      case 0: return EAN_128;
      case 1: return DATA_MATRIX;
      case 2: return PDF417;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BarcodeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BarcodeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BarcodeType>() {
          public BarcodeType findValueByNumber(int number) {
            return BarcodeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return de.ku.sfl.connection.messages.BarcodeTypeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final BarcodeType[] VALUES = values();

  public static BarcodeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BarcodeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:de.ku.sfl.connection.messages.BarcodeType)
}

