// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BarcodeType.proto

package de.ku.sfl.connection.messages;

public final class BarcodeTypeOuterClass {
  private BarcodeTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BarcodeType.proto\022\035de.ku.sfl.connectio" +
      "n.messages*7\n\013BarcodeType\022\013\n\007EAN_128\020\000\022\017" +
      "\n\013DATA_MATRIX\020\001\022\n\n\006PDF417\020\002B\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
