// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageDescription.proto

package de.ku.sfl.connection.messages;

public interface MessageDescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:de.ku.sfl.connection.messages.MessageDescription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .de.ku.sfl.connection.messages.MessageType messageType = 1;</code>
   * @return Whether the messageType field is set.
   */
  boolean hasMessageType();
  /**
   * <code>required .de.ku.sfl.connection.messages.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  de.ku.sfl.connection.messages.MessageType getMessageType();
}
