// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageDescription.proto

package de.ku.sfl.connection.messages;

public final class MessageDescriptionOuterClass {
  private MessageDescriptionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_ku_sfl_connection_messages_MessageDescription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_ku_sfl_connection_messages_MessageDescription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030MessageDescription.proto\022\035de.ku.sfl.co" +
      "nnection.messages\032\021MessageType.proto\"U\n\022" +
      "MessageDescription\022?\n\013messageType\030\001 \002(\0162" +
      "*.de.ku.sfl.connection.messages.MessageT" +
      "ypeB\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.ku.sfl.connection.messages.MessageTypeOuterClass.getDescriptor(),
        });
    internal_static_de_ku_sfl_connection_messages_MessageDescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_de_ku_sfl_connection_messages_MessageDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_ku_sfl_connection_messages_MessageDescription_descriptor,
        new java.lang.String[] { "MessageType", });
    de.ku.sfl.connection.messages.MessageTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
