// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto

package de.ku.sfl.connection.messages;

public final class MessageTypeOuterClass {
  private MessageTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MessageType.proto\022\035de.ku.sfl.connectio" +
      "n.messages*t\n\013MessageType\022\023\n\017RebuildData" +
      "base\020\000\022\024\n\020ReportDiscovered\020\001\022\034\n\030NamedBoo" +
      "leanValueChanged\020\002\022\034\n\030NamedIntegerValueC" +
      "hanged\020\003B\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
