// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageDescription.proto

package de.ku.sfl.connection.messages;

/**
 * Protobuf type {@code de.ku.sfl.connection.messages.MessageDescription}
 */
public final class MessageDescription extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:de.ku.sfl.connection.messages.MessageDescription)
    MessageDescriptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageDescription.newBuilder() to construct.
  private MessageDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageDescription() {
    messageType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageDescription();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageDescription(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            de.ku.sfl.connection.messages.MessageType value = de.ku.sfl.connection.messages.MessageType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              messageType_ = rawValue;
            }
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.ku.sfl.connection.messages.MessageDescriptionOuterClass.internal_static_de_ku_sfl_connection_messages_MessageDescription_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.ku.sfl.connection.messages.MessageDescriptionOuterClass.internal_static_de_ku_sfl_connection_messages_MessageDescription_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.ku.sfl.connection.messages.MessageDescription.class, de.ku.sfl.connection.messages.MessageDescription.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private int messageType_;
  /**
   * <code>required .de.ku.sfl.connection.messages.MessageType messageType = 1;</code>
   * @return Whether the messageType field is set.
   */
  @java.lang.Override public boolean hasMessageType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .de.ku.sfl.connection.messages.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  @java.lang.Override public de.ku.sfl.connection.messages.MessageType getMessageType() {
    @SuppressWarnings("deprecation")
    de.ku.sfl.connection.messages.MessageType result = de.ku.sfl.connection.messages.MessageType.valueOf(messageType_);
    return result == null ? de.ku.sfl.connection.messages.MessageType.RebuildDatabase : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasMessageType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, messageType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, messageType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.ku.sfl.connection.messages.MessageDescription)) {
      return super.equals(obj);
    }
    de.ku.sfl.connection.messages.MessageDescription other = (de.ku.sfl.connection.messages.MessageDescription) obj;

    if (hasMessageType() != other.hasMessageType()) return false;
    if (hasMessageType()) {
      if (messageType_ != other.messageType_) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMessageType()) {
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.MessageDescription parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.ku.sfl.connection.messages.MessageDescription prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code de.ku.sfl.connection.messages.MessageDescription}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:de.ku.sfl.connection.messages.MessageDescription)
      de.ku.sfl.connection.messages.MessageDescriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.ku.sfl.connection.messages.MessageDescriptionOuterClass.internal_static_de_ku_sfl_connection_messages_MessageDescription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.ku.sfl.connection.messages.MessageDescriptionOuterClass.internal_static_de_ku_sfl_connection_messages_MessageDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.ku.sfl.connection.messages.MessageDescription.class, de.ku.sfl.connection.messages.MessageDescription.Builder.class);
    }

    // Construct using de.ku.sfl.connection.messages.MessageDescription.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.ku.sfl.connection.messages.MessageDescriptionOuterClass.internal_static_de_ku_sfl_connection_messages_MessageDescription_descriptor;
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.MessageDescription getDefaultInstanceForType() {
      return de.ku.sfl.connection.messages.MessageDescription.getDefaultInstance();
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.MessageDescription build() {
      de.ku.sfl.connection.messages.MessageDescription result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.MessageDescription buildPartial() {
      de.ku.sfl.connection.messages.MessageDescription result = new de.ku.sfl.connection.messages.MessageDescription(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.messageType_ = messageType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.ku.sfl.connection.messages.MessageDescription) {
        return mergeFrom((de.ku.sfl.connection.messages.MessageDescription)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.ku.sfl.connection.messages.MessageDescription other) {
      if (other == de.ku.sfl.connection.messages.MessageDescription.getDefaultInstance()) return this;
      if (other.hasMessageType()) {
        setMessageType(other.getMessageType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasMessageType()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.ku.sfl.connection.messages.MessageDescription parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.ku.sfl.connection.messages.MessageDescription) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int messageType_ = 0;
    /**
     * <code>required .de.ku.sfl.connection.messages.MessageType messageType = 1;</code>
     * @return Whether the messageType field is set.
     */
    @java.lang.Override public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public de.ku.sfl.connection.messages.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      de.ku.sfl.connection.messages.MessageType result = de.ku.sfl.connection.messages.MessageType.valueOf(messageType_);
      return result == null ? de.ku.sfl.connection.messages.MessageType.RebuildDatabase : result;
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.MessageType messageType = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(de.ku.sfl.connection.messages.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.MessageType messageType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:de.ku.sfl.connection.messages.MessageDescription)
  }

  // @@protoc_insertion_point(class_scope:de.ku.sfl.connection.messages.MessageDescription)
  private static final de.ku.sfl.connection.messages.MessageDescription DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.ku.sfl.connection.messages.MessageDescription();
  }

  public static de.ku.sfl.connection.messages.MessageDescription getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageDescription>
      PARSER = new com.google.protobuf.AbstractParser<MessageDescription>() {
    @java.lang.Override
    public MessageDescription parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageDescription(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageDescription> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageDescription> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.ku.sfl.connection.messages.MessageDescription getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

