// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NamedBooleanValueChangedMessage.proto

package de.ku.sfl.connection.messages;

public interface NamedBooleanValueChangedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:de.ku.sfl.connection.messages.NamedBooleanValueChangedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required bool value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>required bool value = 2;</code>
   * @return The value.
   */
  boolean getValue();
}
