// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RebuildDatabaseMessage.proto

package de.ku.sfl.connection.messages;

public interface RebuildDatabaseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:de.ku.sfl.connection.messages.RebuildDatabaseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .de.ku.sfl.connection.messages.Report reports = 1;</code>
   */
  java.util.List<de.ku.sfl.connection.messages.Report> 
      getReportsList();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.Report reports = 1;</code>
   */
  de.ku.sfl.connection.messages.Report getReports(int index);
  /**
   * <code>repeated .de.ku.sfl.connection.messages.Report reports = 1;</code>
   */
  int getReportsCount();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.Report reports = 1;</code>
   */
  java.util.List<? extends de.ku.sfl.connection.messages.ReportOrBuilder> 
      getReportsOrBuilderList();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.Report reports = 1;</code>
   */
  de.ku.sfl.connection.messages.ReportOrBuilder getReportsOrBuilder(
      int index);

  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedBooleanValue namedBooleanValues = 2;</code>
   */
  java.util.List<de.ku.sfl.connection.messages.NamedBooleanValue> 
      getNamedBooleanValuesList();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedBooleanValue namedBooleanValues = 2;</code>
   */
  de.ku.sfl.connection.messages.NamedBooleanValue getNamedBooleanValues(int index);
  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedBooleanValue namedBooleanValues = 2;</code>
   */
  int getNamedBooleanValuesCount();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedBooleanValue namedBooleanValues = 2;</code>
   */
  java.util.List<? extends de.ku.sfl.connection.messages.NamedBooleanValueOrBuilder> 
      getNamedBooleanValuesOrBuilderList();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedBooleanValue namedBooleanValues = 2;</code>
   */
  de.ku.sfl.connection.messages.NamedBooleanValueOrBuilder getNamedBooleanValuesOrBuilder(
      int index);

  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedIntegerValue namedIntegerValues = 3;</code>
   */
  java.util.List<de.ku.sfl.connection.messages.NamedIntegerValue> 
      getNamedIntegerValuesList();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedIntegerValue namedIntegerValues = 3;</code>
   */
  de.ku.sfl.connection.messages.NamedIntegerValue getNamedIntegerValues(int index);
  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedIntegerValue namedIntegerValues = 3;</code>
   */
  int getNamedIntegerValuesCount();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedIntegerValue namedIntegerValues = 3;</code>
   */
  java.util.List<? extends de.ku.sfl.connection.messages.NamedIntegerValueOrBuilder> 
      getNamedIntegerValuesOrBuilderList();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.NamedIntegerValue namedIntegerValues = 3;</code>
   */
  de.ku.sfl.connection.messages.NamedIntegerValueOrBuilder getNamedIntegerValuesOrBuilder(
      int index);

  /**
   * <code>repeated .de.ku.sfl.connection.messages.Image images = 4;</code>
   */
  java.util.List<de.ku.sfl.connection.messages.Image> 
      getImagesList();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.Image images = 4;</code>
   */
  de.ku.sfl.connection.messages.Image getImages(int index);
  /**
   * <code>repeated .de.ku.sfl.connection.messages.Image images = 4;</code>
   */
  int getImagesCount();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.Image images = 4;</code>
   */
  java.util.List<? extends de.ku.sfl.connection.messages.ImageOrBuilder> 
      getImagesOrBuilderList();
  /**
   * <code>repeated .de.ku.sfl.connection.messages.Image images = 4;</code>
   */
  de.ku.sfl.connection.messages.ImageOrBuilder getImagesOrBuilder(
      int index);
}
