// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportVariant.proto

package de.ku.sfl.connection.messages;

public interface ReportVariantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:de.ku.sfl.connection.messages.ReportVariant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string externalName = 1;</code>
   * @return Whether the externalName field is set.
   */
  boolean hasExternalName();
  /**
   * <code>required string externalName = 1;</code>
   * @return The externalName.
   */
  java.lang.String getExternalName();
  /**
   * <code>required string externalName = 1;</code>
   * @return The bytes for externalName.
   */
  com.google.protobuf.ByteString
      getExternalNameBytes();

  /**
   * <code>required string description = 2;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>required string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>required string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>required int32 priority = 3;</code>
   * @return Whether the priority field is set.
   */
  boolean hasPriority();
  /**
   * <code>required int32 priority = 3;</code>
   * @return The priority.
   */
  int getPriority();

  /**
   * <code>repeated int32 dependencies = 4;</code>
   * @return A list containing the dependencies.
   */
  java.util.List<java.lang.Integer> getDependenciesList();
  /**
   * <code>repeated int32 dependencies = 4;</code>
   * @return The count of dependencies.
   */
  int getDependenciesCount();
  /**
   * <code>repeated int32 dependencies = 4;</code>
   * @param index The index of the element to return.
   * @return The dependencies at the given index.
   */
  int getDependencies(int index);
}
