// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportDiscoveredMessage.proto

package de.ku.sfl.connection.messages;

public final class ReportDiscoveredMessageOuterClass {
  private ReportDiscoveredMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_ku_sfl_connection_messages_ReportDiscoveredMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_ku_sfl_connection_messages_ReportDiscoveredMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ReportDiscoveredMessage.proto\022\035de.ku.s" +
      "fl.connection.messages\":\n\027ReportDiscover" +
      "edMessage\022\013\n\003key\030\001 \002(\t\022\022\n\ndiscovered\030\002 \002" +
      "(\010B\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_de_ku_sfl_connection_messages_ReportDiscoveredMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_de_ku_sfl_connection_messages_ReportDiscoveredMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_ku_sfl_connection_messages_ReportDiscoveredMessage_descriptor,
        new java.lang.String[] { "Key", "Discovered", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
