// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportVariant.proto

package de.ku.sfl.connection.messages;

public final class ReportVariantOuterClass {
  private ReportVariantOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_ku_sfl_connection_messages_ReportVariant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_ku_sfl_connection_messages_ReportVariant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ReportVariant.proto\022\035de.ku.sfl.connect" +
      "ion.messages\"b\n\rReportVariant\022\024\n\014externa" +
      "lName\030\001 \002(\t\022\023\n\013description\030\002 \002(\t\022\020\n\010prio" +
      "rity\030\003 \002(\005\022\024\n\014dependencies\030\004 \003(\005B\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_de_ku_sfl_connection_messages_ReportVariant_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_de_ku_sfl_connection_messages_ReportVariant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_ku_sfl_connection_messages_ReportVariant_descriptor,
        new java.lang.String[] { "ExternalName", "Description", "Priority", "Dependencies", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
