// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportVariant.proto

package de.ku.sfl.connection.messages;

/**
 * Protobuf type {@code de.ku.sfl.connection.messages.ReportVariant}
 */
public final class ReportVariant extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:de.ku.sfl.connection.messages.ReportVariant)
    ReportVariantOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportVariant.newBuilder() to construct.
  private ReportVariant(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportVariant() {
    externalName_ = "";
    description_ = "";
    dependencies_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReportVariant();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportVariant(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            externalName_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            description_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            priority_ = input.readInt32();
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              dependencies_ = newIntList();
              mutable_bitField0_ |= 0x00000008;
            }
            dependencies_.addInt(input.readInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
              dependencies_ = newIntList();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              dependencies_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        dependencies_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.ku.sfl.connection.messages.ReportVariantOuterClass.internal_static_de_ku_sfl_connection_messages_ReportVariant_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.ku.sfl.connection.messages.ReportVariantOuterClass.internal_static_de_ku_sfl_connection_messages_ReportVariant_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.ku.sfl.connection.messages.ReportVariant.class, de.ku.sfl.connection.messages.ReportVariant.Builder.class);
  }

  private int bitField0_;
  public static final int EXTERNALNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object externalName_;
  /**
   * <code>required string externalName = 1;</code>
   * @return Whether the externalName field is set.
   */
  @java.lang.Override
  public boolean hasExternalName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string externalName = 1;</code>
   * @return The externalName.
   */
  @java.lang.Override
  public java.lang.String getExternalName() {
    java.lang.Object ref = externalName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        externalName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string externalName = 1;</code>
   * @return The bytes for externalName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExternalNameBytes() {
    java.lang.Object ref = externalName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object description_;
  /**
   * <code>required string description = 2;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string description = 2;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        description_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string description = 2;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIORITY_FIELD_NUMBER = 3;
  private int priority_;
  /**
   * <code>required int32 priority = 3;</code>
   * @return Whether the priority field is set.
   */
  @java.lang.Override
  public boolean hasPriority() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int32 priority = 3;</code>
   * @return The priority.
   */
  @java.lang.Override
  public int getPriority() {
    return priority_;
  }

  public static final int DEPENDENCIES_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.IntList dependencies_;
  /**
   * <code>repeated int32 dependencies = 4;</code>
   * @return A list containing the dependencies.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getDependenciesList() {
    return dependencies_;
  }
  /**
   * <code>repeated int32 dependencies = 4;</code>
   * @return The count of dependencies.
   */
  public int getDependenciesCount() {
    return dependencies_.size();
  }
  /**
   * <code>repeated int32 dependencies = 4;</code>
   * @param index The index of the element to return.
   * @return The dependencies at the given index.
   */
  public int getDependencies(int index) {
    return dependencies_.getInt(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasExternalName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDescription()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPriority()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, externalName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, priority_);
    }
    for (int i = 0; i < dependencies_.size(); i++) {
      output.writeInt32(4, dependencies_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, externalName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, priority_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < dependencies_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(dependencies_.getInt(i));
      }
      size += dataSize;
      size += 1 * getDependenciesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.ku.sfl.connection.messages.ReportVariant)) {
      return super.equals(obj);
    }
    de.ku.sfl.connection.messages.ReportVariant other = (de.ku.sfl.connection.messages.ReportVariant) obj;

    if (hasExternalName() != other.hasExternalName()) return false;
    if (hasExternalName()) {
      if (!getExternalName()
          .equals(other.getExternalName())) return false;
    }
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (hasPriority() != other.hasPriority()) return false;
    if (hasPriority()) {
      if (getPriority()
          != other.getPriority()) return false;
    }
    if (!getDependenciesList()
        .equals(other.getDependenciesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasExternalName()) {
      hash = (37 * hash) + EXTERNALNAME_FIELD_NUMBER;
      hash = (53 * hash) + getExternalName().hashCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    if (hasPriority()) {
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority();
    }
    if (getDependenciesCount() > 0) {
      hash = (37 * hash) + DEPENDENCIES_FIELD_NUMBER;
      hash = (53 * hash) + getDependenciesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.ReportVariant parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.ku.sfl.connection.messages.ReportVariant prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code de.ku.sfl.connection.messages.ReportVariant}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:de.ku.sfl.connection.messages.ReportVariant)
      de.ku.sfl.connection.messages.ReportVariantOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.ku.sfl.connection.messages.ReportVariantOuterClass.internal_static_de_ku_sfl_connection_messages_ReportVariant_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.ku.sfl.connection.messages.ReportVariantOuterClass.internal_static_de_ku_sfl_connection_messages_ReportVariant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.ku.sfl.connection.messages.ReportVariant.class, de.ku.sfl.connection.messages.ReportVariant.Builder.class);
    }

    // Construct using de.ku.sfl.connection.messages.ReportVariant.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      externalName_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      description_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      priority_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      dependencies_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.ku.sfl.connection.messages.ReportVariantOuterClass.internal_static_de_ku_sfl_connection_messages_ReportVariant_descriptor;
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.ReportVariant getDefaultInstanceForType() {
      return de.ku.sfl.connection.messages.ReportVariant.getDefaultInstance();
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.ReportVariant build() {
      de.ku.sfl.connection.messages.ReportVariant result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.ReportVariant buildPartial() {
      de.ku.sfl.connection.messages.ReportVariant result = new de.ku.sfl.connection.messages.ReportVariant(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.externalName_ = externalName_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.description_ = description_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.priority_ = priority_;
        to_bitField0_ |= 0x00000004;
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        dependencies_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.dependencies_ = dependencies_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.ku.sfl.connection.messages.ReportVariant) {
        return mergeFrom((de.ku.sfl.connection.messages.ReportVariant)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.ku.sfl.connection.messages.ReportVariant other) {
      if (other == de.ku.sfl.connection.messages.ReportVariant.getDefaultInstance()) return this;
      if (other.hasExternalName()) {
        bitField0_ |= 0x00000001;
        externalName_ = other.externalName_;
        onChanged();
      }
      if (other.hasDescription()) {
        bitField0_ |= 0x00000002;
        description_ = other.description_;
        onChanged();
      }
      if (other.hasPriority()) {
        setPriority(other.getPriority());
      }
      if (!other.dependencies_.isEmpty()) {
        if (dependencies_.isEmpty()) {
          dependencies_ = other.dependencies_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureDependenciesIsMutable();
          dependencies_.addAll(other.dependencies_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasExternalName()) {
        return false;
      }
      if (!hasDescription()) {
        return false;
      }
      if (!hasPriority()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.ku.sfl.connection.messages.ReportVariant parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.ku.sfl.connection.messages.ReportVariant) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object externalName_ = "";
    /**
     * <code>required string externalName = 1;</code>
     * @return Whether the externalName field is set.
     */
    public boolean hasExternalName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string externalName = 1;</code>
     * @return The externalName.
     */
    public java.lang.String getExternalName() {
      java.lang.Object ref = externalName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          externalName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string externalName = 1;</code>
     * @return The bytes for externalName.
     */
    public com.google.protobuf.ByteString
        getExternalNameBytes() {
      java.lang.Object ref = externalName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string externalName = 1;</code>
     * @param value The externalName to set.
     * @return This builder for chaining.
     */
    public Builder setExternalName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      externalName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string externalName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExternalName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      externalName_ = getDefaultInstance().getExternalName();
      onChanged();
      return this;
    }
    /**
     * <code>required string externalName = 1;</code>
     * @param value The bytes for externalName to set.
     * @return This builder for chaining.
     */
    public Builder setExternalNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      externalName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>required string description = 2;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string description = 2;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string description = 2;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string description = 2;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string description = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000002);
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>required string description = 2;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      description_ = value;
      onChanged();
      return this;
    }

    private int priority_ ;
    /**
     * <code>required int32 priority = 3;</code>
     * @return Whether the priority field is set.
     */
    @java.lang.Override
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 priority = 3;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }
    /**
     * <code>required int32 priority = 3;</code>
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(int value) {
      bitField0_ |= 0x00000004;
      priority_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 priority = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriority() {
      bitField0_ = (bitField0_ & ~0x00000004);
      priority_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList dependencies_ = emptyIntList();
    private void ensureDependenciesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        dependencies_ = mutableCopy(dependencies_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated int32 dependencies = 4;</code>
     * @return A list containing the dependencies.
     */
    public java.util.List<java.lang.Integer>
        getDependenciesList() {
      return ((bitField0_ & 0x00000008) != 0) ?
               java.util.Collections.unmodifiableList(dependencies_) : dependencies_;
    }
    /**
     * <code>repeated int32 dependencies = 4;</code>
     * @return The count of dependencies.
     */
    public int getDependenciesCount() {
      return dependencies_.size();
    }
    /**
     * <code>repeated int32 dependencies = 4;</code>
     * @param index The index of the element to return.
     * @return The dependencies at the given index.
     */
    public int getDependencies(int index) {
      return dependencies_.getInt(index);
    }
    /**
     * <code>repeated int32 dependencies = 4;</code>
     * @param index The index to set the value at.
     * @param value The dependencies to set.
     * @return This builder for chaining.
     */
    public Builder setDependencies(
        int index, int value) {
      ensureDependenciesIsMutable();
      dependencies_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 dependencies = 4;</code>
     * @param value The dependencies to add.
     * @return This builder for chaining.
     */
    public Builder addDependencies(int value) {
      ensureDependenciesIsMutable();
      dependencies_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 dependencies = 4;</code>
     * @param values The dependencies to add.
     * @return This builder for chaining.
     */
    public Builder addAllDependencies(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureDependenciesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, dependencies_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 dependencies = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDependencies() {
      dependencies_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:de.ku.sfl.connection.messages.ReportVariant)
  }

  // @@protoc_insertion_point(class_scope:de.ku.sfl.connection.messages.ReportVariant)
  private static final de.ku.sfl.connection.messages.ReportVariant DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.ku.sfl.connection.messages.ReportVariant();
  }

  public static de.ku.sfl.connection.messages.ReportVariant getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ReportVariant>
      PARSER = new com.google.protobuf.AbstractParser<ReportVariant>() {
    @java.lang.Override
    public ReportVariant parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportVariant(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportVariant> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportVariant> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.ku.sfl.connection.messages.ReportVariant getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

