// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Report.proto

package de.ku.sfl.connection.messages;

/**
 * Protobuf type {@code de.ku.sfl.connection.messages.Report}
 */
public final class Report extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:de.ku.sfl.connection.messages.Report)
    ReportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Report.newBuilder() to construct.
  private Report(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Report() {
    key_ = "";
    internalName_ = "";
    barcodeType_ = 0;
    scannerType_ = 0;
    category_ = "";
    location_ = "";
    variants_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Report();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Report(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            key_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            internalName_ = bs;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            de.ku.sfl.connection.messages.BarcodeType value = de.ku.sfl.connection.messages.BarcodeType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000004;
              barcodeType_ = rawValue;
            }
            break;
          }
          case 56: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            de.ku.sfl.connection.messages.ScannerType value = de.ku.sfl.connection.messages.ScannerType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(7, rawValue);
            } else {
              bitField0_ |= 0x00000008;
              scannerType_ = rawValue;
            }
            break;
          }
          case 66: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            category_ = bs;
            break;
          }
          case 74: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            location_ = bs;
            break;
          }
          case 80: {
            bitField0_ |= 0x00000040;
            visible_ = input.readBool();
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000080) != 0)) {
              variants_ = new java.util.ArrayList<de.ku.sfl.connection.messages.ReportVariant>();
              mutable_bitField0_ |= 0x00000080;
            }
            variants_.add(
                input.readMessage(de.ku.sfl.connection.messages.ReportVariant.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) != 0)) {
        variants_ = java.util.Collections.unmodifiableList(variants_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.ku.sfl.connection.messages.ReportOuterClass.internal_static_de_ku_sfl_connection_messages_Report_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.ku.sfl.connection.messages.ReportOuterClass.internal_static_de_ku_sfl_connection_messages_Report_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.ku.sfl.connection.messages.Report.class, de.ku.sfl.connection.messages.Report.Builder.class);
  }

  private int bitField0_;
  public static final int KEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object key_;
  /**
   * <code>required string key = 2;</code>
   * @return Whether the key field is set.
   */
  @java.lang.Override
  public boolean hasKey() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string key = 2;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        key_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string key = 2;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERNALNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object internalName_;
  /**
   * <code>required string internalName = 4;</code>
   * @return Whether the internalName field is set.
   */
  @java.lang.Override
  public boolean hasInternalName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string internalName = 4;</code>
   * @return The internalName.
   */
  @java.lang.Override
  public java.lang.String getInternalName() {
    java.lang.Object ref = internalName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        internalName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string internalName = 4;</code>
   * @return The bytes for internalName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInternalNameBytes() {
    java.lang.Object ref = internalName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      internalName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BARCODETYPE_FIELD_NUMBER = 6;
  private int barcodeType_;
  /**
   * <code>required .de.ku.sfl.connection.messages.BarcodeType barcodeType = 6;</code>
   * @return Whether the barcodeType field is set.
   */
  @java.lang.Override public boolean hasBarcodeType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required .de.ku.sfl.connection.messages.BarcodeType barcodeType = 6;</code>
   * @return The barcodeType.
   */
  @java.lang.Override public de.ku.sfl.connection.messages.BarcodeType getBarcodeType() {
    @SuppressWarnings("deprecation")
    de.ku.sfl.connection.messages.BarcodeType result = de.ku.sfl.connection.messages.BarcodeType.valueOf(barcodeType_);
    return result == null ? de.ku.sfl.connection.messages.BarcodeType.EAN_128 : result;
  }

  public static final int SCANNERTYPE_FIELD_NUMBER = 7;
  private int scannerType_;
  /**
   * <code>required .de.ku.sfl.connection.messages.ScannerType scannerType = 7;</code>
   * @return Whether the scannerType field is set.
   */
  @java.lang.Override public boolean hasScannerType() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required .de.ku.sfl.connection.messages.ScannerType scannerType = 7;</code>
   * @return The scannerType.
   */
  @java.lang.Override public de.ku.sfl.connection.messages.ScannerType getScannerType() {
    @SuppressWarnings("deprecation")
    de.ku.sfl.connection.messages.ScannerType result = de.ku.sfl.connection.messages.ScannerType.valueOf(scannerType_);
    return result == null ? de.ku.sfl.connection.messages.ScannerType.SCIENTIFIC : result;
  }

  public static final int CATEGORY_FIELD_NUMBER = 8;
  private volatile java.lang.Object category_;
  /**
   * <code>required string category = 8;</code>
   * @return Whether the category field is set.
   */
  @java.lang.Override
  public boolean hasCategory() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required string category = 8;</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        category_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string category = 8;</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION_FIELD_NUMBER = 9;
  private volatile java.lang.Object location_;
  /**
   * <code>required string location = 9;</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required string location = 9;</code>
   * @return The location.
   */
  @java.lang.Override
  public java.lang.String getLocation() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        location_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string location = 9;</code>
   * @return The bytes for location.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocationBytes() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VISIBLE_FIELD_NUMBER = 10;
  private boolean visible_;
  /**
   * <code>required bool visible = 10;</code>
   * @return Whether the visible field is set.
   */
  @java.lang.Override
  public boolean hasVisible() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>required bool visible = 10;</code>
   * @return The visible.
   */
  @java.lang.Override
  public boolean getVisible() {
    return visible_;
  }

  public static final int VARIANTS_FIELD_NUMBER = 11;
  private java.util.List<de.ku.sfl.connection.messages.ReportVariant> variants_;
  /**
   * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
   */
  @java.lang.Override
  public java.util.List<de.ku.sfl.connection.messages.ReportVariant> getVariantsList() {
    return variants_;
  }
  /**
   * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
   */
  @java.lang.Override
  public java.util.List<? extends de.ku.sfl.connection.messages.ReportVariantOrBuilder> 
      getVariantsOrBuilderList() {
    return variants_;
  }
  /**
   * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
   */
  @java.lang.Override
  public int getVariantsCount() {
    return variants_.size();
  }
  /**
   * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
   */
  @java.lang.Override
  public de.ku.sfl.connection.messages.ReportVariant getVariants(int index) {
    return variants_.get(index);
  }
  /**
   * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
   */
  @java.lang.Override
  public de.ku.sfl.connection.messages.ReportVariantOrBuilder getVariantsOrBuilder(
      int index) {
    return variants_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasKey()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasInternalName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBarcodeType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasScannerType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCategory()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasLocation()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasVisible()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getVariantsCount(); i++) {
      if (!getVariants(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, internalName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(6, barcodeType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(7, scannerType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, category_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, location_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeBool(10, visible_);
    }
    for (int i = 0; i < variants_.size(); i++) {
      output.writeMessage(11, variants_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, internalName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, barcodeType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, scannerType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, category_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, location_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, visible_);
    }
    for (int i = 0; i < variants_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, variants_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.ku.sfl.connection.messages.Report)) {
      return super.equals(obj);
    }
    de.ku.sfl.connection.messages.Report other = (de.ku.sfl.connection.messages.Report) obj;

    if (hasKey() != other.hasKey()) return false;
    if (hasKey()) {
      if (!getKey()
          .equals(other.getKey())) return false;
    }
    if (hasInternalName() != other.hasInternalName()) return false;
    if (hasInternalName()) {
      if (!getInternalName()
          .equals(other.getInternalName())) return false;
    }
    if (hasBarcodeType() != other.hasBarcodeType()) return false;
    if (hasBarcodeType()) {
      if (barcodeType_ != other.barcodeType_) return false;
    }
    if (hasScannerType() != other.hasScannerType()) return false;
    if (hasScannerType()) {
      if (scannerType_ != other.scannerType_) return false;
    }
    if (hasCategory() != other.hasCategory()) return false;
    if (hasCategory()) {
      if (!getCategory()
          .equals(other.getCategory())) return false;
    }
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (hasVisible() != other.hasVisible()) return false;
    if (hasVisible()) {
      if (getVisible()
          != other.getVisible()) return false;
    }
    if (!getVariantsList()
        .equals(other.getVariantsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasKey()) {
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
    }
    if (hasInternalName()) {
      hash = (37 * hash) + INTERNALNAME_FIELD_NUMBER;
      hash = (53 * hash) + getInternalName().hashCode();
    }
    if (hasBarcodeType()) {
      hash = (37 * hash) + BARCODETYPE_FIELD_NUMBER;
      hash = (53 * hash) + barcodeType_;
    }
    if (hasScannerType()) {
      hash = (37 * hash) + SCANNERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + scannerType_;
    }
    if (hasCategory()) {
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
    }
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    if (hasVisible()) {
      hash = (37 * hash) + VISIBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVisible());
    }
    if (getVariantsCount() > 0) {
      hash = (37 * hash) + VARIANTS_FIELD_NUMBER;
      hash = (53 * hash) + getVariantsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.ku.sfl.connection.messages.Report parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.Report parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.Report parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.ku.sfl.connection.messages.Report parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.ku.sfl.connection.messages.Report prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code de.ku.sfl.connection.messages.Report}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:de.ku.sfl.connection.messages.Report)
      de.ku.sfl.connection.messages.ReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.ku.sfl.connection.messages.ReportOuterClass.internal_static_de_ku_sfl_connection_messages_Report_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.ku.sfl.connection.messages.ReportOuterClass.internal_static_de_ku_sfl_connection_messages_Report_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.ku.sfl.connection.messages.Report.class, de.ku.sfl.connection.messages.Report.Builder.class);
    }

    // Construct using de.ku.sfl.connection.messages.Report.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVariantsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      key_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      internalName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      barcodeType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      scannerType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      category_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      location_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      visible_ = false;
      bitField0_ = (bitField0_ & ~0x00000040);
      if (variantsBuilder_ == null) {
        variants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        variantsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.ku.sfl.connection.messages.ReportOuterClass.internal_static_de_ku_sfl_connection_messages_Report_descriptor;
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.Report getDefaultInstanceForType() {
      return de.ku.sfl.connection.messages.Report.getDefaultInstance();
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.Report build() {
      de.ku.sfl.connection.messages.Report result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.ku.sfl.connection.messages.Report buildPartial() {
      de.ku.sfl.connection.messages.Report result = new de.ku.sfl.connection.messages.Report(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.key_ = key_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.internalName_ = internalName_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.barcodeType_ = barcodeType_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.scannerType_ = scannerType_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.category_ = category_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.location_ = location_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.visible_ = visible_;
        to_bitField0_ |= 0x00000040;
      }
      if (variantsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          variants_ = java.util.Collections.unmodifiableList(variants_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.variants_ = variants_;
      } else {
        result.variants_ = variantsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.ku.sfl.connection.messages.Report) {
        return mergeFrom((de.ku.sfl.connection.messages.Report)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.ku.sfl.connection.messages.Report other) {
      if (other == de.ku.sfl.connection.messages.Report.getDefaultInstance()) return this;
      if (other.hasKey()) {
        bitField0_ |= 0x00000001;
        key_ = other.key_;
        onChanged();
      }
      if (other.hasInternalName()) {
        bitField0_ |= 0x00000002;
        internalName_ = other.internalName_;
        onChanged();
      }
      if (other.hasBarcodeType()) {
        setBarcodeType(other.getBarcodeType());
      }
      if (other.hasScannerType()) {
        setScannerType(other.getScannerType());
      }
      if (other.hasCategory()) {
        bitField0_ |= 0x00000010;
        category_ = other.category_;
        onChanged();
      }
      if (other.hasLocation()) {
        bitField0_ |= 0x00000020;
        location_ = other.location_;
        onChanged();
      }
      if (other.hasVisible()) {
        setVisible(other.getVisible());
      }
      if (variantsBuilder_ == null) {
        if (!other.variants_.isEmpty()) {
          if (variants_.isEmpty()) {
            variants_ = other.variants_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureVariantsIsMutable();
            variants_.addAll(other.variants_);
          }
          onChanged();
        }
      } else {
        if (!other.variants_.isEmpty()) {
          if (variantsBuilder_.isEmpty()) {
            variantsBuilder_.dispose();
            variantsBuilder_ = null;
            variants_ = other.variants_;
            bitField0_ = (bitField0_ & ~0x00000080);
            variantsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVariantsFieldBuilder() : null;
          } else {
            variantsBuilder_.addAllMessages(other.variants_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasKey()) {
        return false;
      }
      if (!hasInternalName()) {
        return false;
      }
      if (!hasBarcodeType()) {
        return false;
      }
      if (!hasScannerType()) {
        return false;
      }
      if (!hasCategory()) {
        return false;
      }
      if (!hasLocation()) {
        return false;
      }
      if (!hasVisible()) {
        return false;
      }
      for (int i = 0; i < getVariantsCount(); i++) {
        if (!getVariants(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.ku.sfl.connection.messages.Report parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.ku.sfl.connection.messages.Report) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object key_ = "";
    /**
     * <code>required string key = 2;</code>
     * @return Whether the key field is set.
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string key = 2;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string key = 2;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string key = 2;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      bitField0_ = (bitField0_ & ~0x00000001);
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>required string key = 2;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      key_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object internalName_ = "";
    /**
     * <code>required string internalName = 4;</code>
     * @return Whether the internalName field is set.
     */
    public boolean hasInternalName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string internalName = 4;</code>
     * @return The internalName.
     */
    public java.lang.String getInternalName() {
      java.lang.Object ref = internalName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          internalName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string internalName = 4;</code>
     * @return The bytes for internalName.
     */
    public com.google.protobuf.ByteString
        getInternalNameBytes() {
      java.lang.Object ref = internalName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        internalName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string internalName = 4;</code>
     * @param value The internalName to set.
     * @return This builder for chaining.
     */
    public Builder setInternalName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      internalName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string internalName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInternalName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalName_ = getDefaultInstance().getInternalName();
      onChanged();
      return this;
    }
    /**
     * <code>required string internalName = 4;</code>
     * @param value The bytes for internalName to set.
     * @return This builder for chaining.
     */
    public Builder setInternalNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      internalName_ = value;
      onChanged();
      return this;
    }

    private int barcodeType_ = 0;
    /**
     * <code>required .de.ku.sfl.connection.messages.BarcodeType barcodeType = 6;</code>
     * @return Whether the barcodeType field is set.
     */
    @java.lang.Override public boolean hasBarcodeType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.BarcodeType barcodeType = 6;</code>
     * @return The barcodeType.
     */
    @java.lang.Override
    public de.ku.sfl.connection.messages.BarcodeType getBarcodeType() {
      @SuppressWarnings("deprecation")
      de.ku.sfl.connection.messages.BarcodeType result = de.ku.sfl.connection.messages.BarcodeType.valueOf(barcodeType_);
      return result == null ? de.ku.sfl.connection.messages.BarcodeType.EAN_128 : result;
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.BarcodeType barcodeType = 6;</code>
     * @param value The barcodeType to set.
     * @return This builder for chaining.
     */
    public Builder setBarcodeType(de.ku.sfl.connection.messages.BarcodeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      barcodeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.BarcodeType barcodeType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBarcodeType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      barcodeType_ = 0;
      onChanged();
      return this;
    }

    private int scannerType_ = 0;
    /**
     * <code>required .de.ku.sfl.connection.messages.ScannerType scannerType = 7;</code>
     * @return Whether the scannerType field is set.
     */
    @java.lang.Override public boolean hasScannerType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.ScannerType scannerType = 7;</code>
     * @return The scannerType.
     */
    @java.lang.Override
    public de.ku.sfl.connection.messages.ScannerType getScannerType() {
      @SuppressWarnings("deprecation")
      de.ku.sfl.connection.messages.ScannerType result = de.ku.sfl.connection.messages.ScannerType.valueOf(scannerType_);
      return result == null ? de.ku.sfl.connection.messages.ScannerType.SCIENTIFIC : result;
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.ScannerType scannerType = 7;</code>
     * @param value The scannerType to set.
     * @return This builder for chaining.
     */
    public Builder setScannerType(de.ku.sfl.connection.messages.ScannerType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      scannerType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .de.ku.sfl.connection.messages.ScannerType scannerType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearScannerType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      scannerType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <code>required string category = 8;</code>
     * @return Whether the category field is set.
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string category = 8;</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          category_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string category = 8;</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string category = 8;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string category = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      bitField0_ = (bitField0_ & ~0x00000010);
      category_ = getDefaultInstance().getCategory();
      onChanged();
      return this;
    }
    /**
     * <code>required string category = 8;</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      category_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object location_ = "";
    /**
     * <code>required string location = 9;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string location = 9;</code>
     * @return The location.
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          location_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string location = 9;</code>
     * @return The bytes for location.
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string location = 9;</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      location_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string location = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      bitField0_ = (bitField0_ & ~0x00000020);
      location_ = getDefaultInstance().getLocation();
      onChanged();
      return this;
    }
    /**
     * <code>required string location = 9;</code>
     * @param value The bytes for location to set.
     * @return This builder for chaining.
     */
    public Builder setLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      location_ = value;
      onChanged();
      return this;
    }

    private boolean visible_ ;
    /**
     * <code>required bool visible = 10;</code>
     * @return Whether the visible field is set.
     */
    @java.lang.Override
    public boolean hasVisible() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required bool visible = 10;</code>
     * @return The visible.
     */
    @java.lang.Override
    public boolean getVisible() {
      return visible_;
    }
    /**
     * <code>required bool visible = 10;</code>
     * @param value The visible to set.
     * @return This builder for chaining.
     */
    public Builder setVisible(boolean value) {
      bitField0_ |= 0x00000040;
      visible_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool visible = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearVisible() {
      bitField0_ = (bitField0_ & ~0x00000040);
      visible_ = false;
      onChanged();
      return this;
    }

    private java.util.List<de.ku.sfl.connection.messages.ReportVariant> variants_ =
      java.util.Collections.emptyList();
    private void ensureVariantsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        variants_ = new java.util.ArrayList<de.ku.sfl.connection.messages.ReportVariant>(variants_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.ku.sfl.connection.messages.ReportVariant, de.ku.sfl.connection.messages.ReportVariant.Builder, de.ku.sfl.connection.messages.ReportVariantOrBuilder> variantsBuilder_;

    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public java.util.List<de.ku.sfl.connection.messages.ReportVariant> getVariantsList() {
      if (variantsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variants_);
      } else {
        return variantsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public int getVariantsCount() {
      if (variantsBuilder_ == null) {
        return variants_.size();
      } else {
        return variantsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public de.ku.sfl.connection.messages.ReportVariant getVariants(int index) {
      if (variantsBuilder_ == null) {
        return variants_.get(index);
      } else {
        return variantsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder setVariants(
        int index, de.ku.sfl.connection.messages.ReportVariant value) {
      if (variantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantsIsMutable();
        variants_.set(index, value);
        onChanged();
      } else {
        variantsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder setVariants(
        int index, de.ku.sfl.connection.messages.ReportVariant.Builder builderForValue) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        variants_.set(index, builderForValue.build());
        onChanged();
      } else {
        variantsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder addVariants(de.ku.sfl.connection.messages.ReportVariant value) {
      if (variantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantsIsMutable();
        variants_.add(value);
        onChanged();
      } else {
        variantsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder addVariants(
        int index, de.ku.sfl.connection.messages.ReportVariant value) {
      if (variantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantsIsMutable();
        variants_.add(index, value);
        onChanged();
      } else {
        variantsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder addVariants(
        de.ku.sfl.connection.messages.ReportVariant.Builder builderForValue) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        variants_.add(builderForValue.build());
        onChanged();
      } else {
        variantsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder addVariants(
        int index, de.ku.sfl.connection.messages.ReportVariant.Builder builderForValue) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        variants_.add(index, builderForValue.build());
        onChanged();
      } else {
        variantsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder addAllVariants(
        java.lang.Iterable<? extends de.ku.sfl.connection.messages.ReportVariant> values) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variants_);
        onChanged();
      } else {
        variantsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder clearVariants() {
      if (variantsBuilder_ == null) {
        variants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        variantsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public Builder removeVariants(int index) {
      if (variantsBuilder_ == null) {
        ensureVariantsIsMutable();
        variants_.remove(index);
        onChanged();
      } else {
        variantsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public de.ku.sfl.connection.messages.ReportVariant.Builder getVariantsBuilder(
        int index) {
      return getVariantsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public de.ku.sfl.connection.messages.ReportVariantOrBuilder getVariantsOrBuilder(
        int index) {
      if (variantsBuilder_ == null) {
        return variants_.get(index);  } else {
        return variantsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public java.util.List<? extends de.ku.sfl.connection.messages.ReportVariantOrBuilder> 
         getVariantsOrBuilderList() {
      if (variantsBuilder_ != null) {
        return variantsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variants_);
      }
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public de.ku.sfl.connection.messages.ReportVariant.Builder addVariantsBuilder() {
      return getVariantsFieldBuilder().addBuilder(
          de.ku.sfl.connection.messages.ReportVariant.getDefaultInstance());
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public de.ku.sfl.connection.messages.ReportVariant.Builder addVariantsBuilder(
        int index) {
      return getVariantsFieldBuilder().addBuilder(
          index, de.ku.sfl.connection.messages.ReportVariant.getDefaultInstance());
    }
    /**
     * <code>repeated .de.ku.sfl.connection.messages.ReportVariant variants = 11;</code>
     */
    public java.util.List<de.ku.sfl.connection.messages.ReportVariant.Builder> 
         getVariantsBuilderList() {
      return getVariantsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.ku.sfl.connection.messages.ReportVariant, de.ku.sfl.connection.messages.ReportVariant.Builder, de.ku.sfl.connection.messages.ReportVariantOrBuilder> 
        getVariantsFieldBuilder() {
      if (variantsBuilder_ == null) {
        variantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            de.ku.sfl.connection.messages.ReportVariant, de.ku.sfl.connection.messages.ReportVariant.Builder, de.ku.sfl.connection.messages.ReportVariantOrBuilder>(
                variants_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        variants_ = null;
      }
      return variantsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:de.ku.sfl.connection.messages.Report)
  }

  // @@protoc_insertion_point(class_scope:de.ku.sfl.connection.messages.Report)
  private static final de.ku.sfl.connection.messages.Report DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.ku.sfl.connection.messages.Report();
  }

  public static de.ku.sfl.connection.messages.Report getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Report>
      PARSER = new com.google.protobuf.AbstractParser<Report>() {
    @java.lang.Override
    public Report parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Report(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Report> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Report> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.ku.sfl.connection.messages.Report getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

