// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScannerType.proto

package de.ku.sfl.connection.messages;

/**
 * Protobuf enum {@code de.ku.sfl.connection.messages.ScannerType}
 */
public enum ScannerType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SCIENTIFIC = 0;</code>
   */
  SCIENTIFIC(0),
  /**
   * <code>TECHNICAL = 1;</code>
   */
  TECHNICAL(1),
  /**
   * <code>MEDICAL = 2;</code>
   */
  MEDICAL(2),
  /**
   * <code>ADMINISTRATIVE = 3;</code>
   */
  ADMINISTRATIVE(3),
  ;

  /**
   * <code>SCIENTIFIC = 0;</code>
   */
  public static final int SCIENTIFIC_VALUE = 0;
  /**
   * <code>TECHNICAL = 1;</code>
   */
  public static final int TECHNICAL_VALUE = 1;
  /**
   * <code>MEDICAL = 2;</code>
   */
  public static final int MEDICAL_VALUE = 2;
  /**
   * <code>ADMINISTRATIVE = 3;</code>
   */
  public static final int ADMINISTRATIVE_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ScannerType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ScannerType forNumber(int value) {
    switch (value) {
      case 0: return SCIENTIFIC;
      case 1: return TECHNICAL;
      case 2: return MEDICAL;
      case 3: return ADMINISTRATIVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ScannerType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ScannerType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ScannerType>() {
          public ScannerType findValueByNumber(int number) {
            return ScannerType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return de.ku.sfl.connection.messages.ScannerTypeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ScannerType[] VALUES = values();

  public static ScannerType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ScannerType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:de.ku.sfl.connection.messages.ScannerType)
}

