// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScannerType.proto

package de.ku.sfl.connection.messages;

public final class ScannerTypeOuterClass {
  private ScannerTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ScannerType.proto\022\035de.ku.sfl.connectio" +
      "n.messages*M\n\013ScannerType\022\016\n\nSCIENTIFIC\020" +
      "\000\022\r\n\tTECHNICAL\020\001\022\013\n\007MEDICAL\020\002\022\022\n\016ADMINIS" +
      "TRATIVE\020\003B\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
